sumArray.exe: sumArray.o vettore.o utility.o
	gcc sumArray.o vettore.o utility.o -o sumArray.exe

sumArray.o: sumArray.c
	gcc -c sumArray.c

vettore.o: vettore.c
	gcc -c vettore.c

utility.o: utility.c
	gcc -c utility.c