insert.exe: insert.o vettore.o utility.o
	gcc insert.o vettore.o utility.o -o insert.exe

insert.o: insert.c
	gcc -c insert.c

vettore.o: vettore.c
	gcc -c vettore.c

utility.o: utility.c
	gcc -c utility.c