ordinaArray.exe: ordinaArray.o vettore.o utility.o
	gcc ordinaArray.o vettore.o utility.o -o ordinaArray.exe

ordinaArray.o: ordinaArray.c
	gcc -c ordinaArray.c

vettore.o: vettore.c
	gcc -c vettore.c

utility.o: utility.c
	gcc -c utility.c