distanze.exe: distanze.o punto.o utility.o
	gcc distanze.o punto.o utility.o -o distanze.exe

distanze.o: distanze.c
	gcc -c distanze.c

punto.o: punto.c
	gcc -c punto.c

utility.o: utility.c
	gcc -c utility.c
